import { Metadata } from "next";
import { siteConfig } from "@/lib/site";

export const metadataKeywords = [
    "Blog",
    "React",
    "Next.js",
    "Tailwind",
    "Shadcn",
    "Next.js Blog",
    "React Blog",
    "Web Development",
    "Tutorials",
    "MDX Blog",
    "JavaScript",
    "TypeScript",
    "Frontend",
    "UI Components",
    "Open Source",
    "Programming",
    "Coding",
    "Web Design",
    "Software Engineering",
    "Tech Articles",
    "Development Tips",
    "Web Apps",
    "Next.js Tutorials",
    "React Tutorials",
    "Tailwind CSS",
    "Shadcn UI",
    "MagicUI",
    "Python",
    "Blockchain",
    "Cryptocurrency",
    "DeFi",
    "NFTs",
    "Web3",
    "Artificial Intelligence",
]

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description,
  keywords: metadataKeywords,
  authors: [
    {
      name: 'Al-Hussein A.',
      url: 'https://al-husayn.vercel.app/',
    },
  ],
  creator: 'Al-Hussein A.',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  twitter: {
    card: 'summary_large_image',
    title: siteConfig.name,
    description: siteConfig.description,
    creator: '@al_drake3',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};