export const metadataKeywords = [
    'JavaScript tutorials',
    'TypeScript tutorials',
    'React tutorials',
    'Next.js tutorials',
    'Web development blog',
    'Frontend engineering',
    'Software engineering',
    'Programming guides',
    'MDX blog',
    'JavaScript best practices',
    'TypeScript best practices',
    'React best practices',
    'Next.js best practices',
    'Clean code',
    'Developer productivity',
    'Tech articles',
    'Coding tutorials',
    'Web performance',
    'Developer blog',
] as const;
